version: "3"
services:
  webapp:
    build: webapp/.
    volumes:
      - ./webapp/src:/app/src
      - ./webapp/public:/app/public
    ports:
      - 8081:3000
  api:
    container_name: api
    build: api/.
    volumes:
      - ./api:/weltfy
    ports:
      - 5000:5000
